"""Minimal, explicit Minecraft resource-pack output."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from PIL import Image

from .contracts import AssetForm, AssetRequest, UvRegionSpec, to_jsonable


def _write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _safe_pack_path(root: Path, relative: str | Path) -> Path:
    """Resolve a pack member and reject traversal outside the output folder."""
    candidate = (root / Path(relative)).resolve()
    root = root.resolve()
    if candidate == root or root not in candidate.parents:
        raise ValueError("resource-pack path escapes output directory: %s" % relative)
    return candidate


def build_resourcepack(request: AssetRequest, sprite_path: Path, out_dir: Path,
                       pack_format: int = 15, uv_regions: list[UvRegionSpec] | None = None) -> list[Path]:
    """Create a small valid base pack and return every written path.

    A custom entity renderer is outside a generic texture pack's authority, so
    entity_uv writes the texture plus its explicit source UV layout rather than
    inventing a model or silently targeting a different entity.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    mcmeta = out_dir / "pack.mcmeta"
    _write_json(
        mcmeta,
        {
            "pack": {
                "pack_format": pack_format,
                "description": "Generated by mc-art-studio-next",
            }
        },
    )
    written.append(mcmeta)
    namespace = request.namespace
    name = request.name
    if request.form in {AssetForm.ITEM, AssetForm.CROSS}:
        texture = _safe_pack_path(out_dir, Path("assets") / namespace / "textures" / "item" / (name + ".png"))
        model = _safe_pack_path(out_dir, Path("assets") / namespace / "models" / "item" / (name + ".json"))
        texture.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(sprite_path, texture)
        _write_json(
            model,
            {
                "parent": "minecraft:item/generated",
                "textures": {"layer0": "%s:item/%s" % (namespace, name)},
            },
        )
        written.extend([texture, model])
    elif request.form == AssetForm.BLOCK_MULTI:
        texture = _safe_pack_path(out_dir, Path("assets") / namespace / "textures" / "block" / (name + ".png"))
        texture.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(sprite_path, texture)
        written.append(texture)
        # A vanilla block texture is often one tile assigned to every cube
        # face (the ``cube_all`` contract). Detect that layout from the supplied
        # UV rectangles instead of naming a block type, and keep the pack's
        # model faithful to the single source file.
        shared_tile = False
        if uv_regions and len(uv_regions) >= 3:
            boxes = {tuple(region.bbox) for region in uv_regions}
            try:
                with Image.open(sprite_path) as atlas:
                    shared_tile = (
                        len(boxes) == 1
                        and next(iter(boxes)) == (0, 0, atlas.width, atlas.height)
                    )
            except (OSError, ValueError):
                shared_tile = False
        if shared_tile:
            model = _safe_pack_path(out_dir, Path("assets") / namespace / "models" / "block" / (name + ".json"))
            _write_json(
                model,
                {
                    "parent": "block/cube_all",
                    "textures": {"all": "%s:block/%s" % (namespace, name)},
                },
            )
            written.append(model)
            blockstates = _safe_pack_path(
                out_dir,
                Path("assets") / namespace / "blockstates" / (name + ".json"),
            )
            _write_json(blockstates, {"variants": {"": {"model": "%s:block/%s" % (namespace, name)}}})
            written.append(blockstates)
            item_model = _safe_pack_path(
                out_dir,
                Path("assets") / namespace / "models" / "item" / (name + ".json"),
            )
            _write_json(item_model, {"parent": "%s:block/%s" % (namespace, name)})
            written.append(item_model)
            note = out_dir / "BLOCK_MULTI_NOTE.txt"
            note.write_text(
                "The generated block uses one texture tile for all six cube faces (block/cube_all).\n",
                encoding="utf-8",
            )
            written.append(note)
            return written
        face_regions = {
            region.face.lower(): region
            for region in (uv_regions or [])
            if region.face.lower() in {"top", "bottom", "front", "back", "right", "left", "side", "north", "south", "east", "west"}
        }
        top = face_regions.get("top")
        bottom = face_regions.get("bottom")
        front = face_regions.get("front") or face_regions.get("north") or face_regions.get("south")
        side = face_regions.get("right") or face_regions.get("east") or face_regions.get("side") or face_regions.get("left")
        if top and front and side:
            with Image.open(sprite_path) as atlas:
                face_specs = [("top", top), ("front", front), ("side", side)]
                if bottom is not None:
                    face_specs.append(("bottom", bottom))
                for label, region in face_specs:
                    face_path = _safe_pack_path(
                        out_dir,
                        Path("assets") / namespace / "textures" / "block" / (name + "_" + label + ".png"),
                    )
                    face_path.parent.mkdir(parents=True, exist_ok=True)
                    atlas.crop(tuple(region.bbox)).save(face_path, "PNG")
                    written.append(face_path)
            model = _safe_pack_path(out_dir, Path("assets") / namespace / "models" / "block" / (name + ".json"))
            _write_json(
                model,
                {
                    "parent": "block/cube",
                    "textures": {
                        "top": "%s:block/%s_top" % (namespace, name),
                        "bottom": "%s:block/%s_%s" % (namespace, name, "bottom" if bottom else "front"),
                        "north": "%s:block/%s_front" % (namespace, name),
                        "south": "%s:block/%s_front" % (namespace, name),
                        "west": "%s:block/%s_side" % (namespace, name),
                        "east": "%s:block/%s_side" % (namespace, name),
                        "particle": "%s:block/%s_front" % (namespace, name),
                    },
                },
            )
            written.append(model)
            blockstates = _safe_pack_path(
                out_dir,
                Path("assets") / namespace / "blockstates" / (name + ".json"),
            )
            _write_json(blockstates, {"variants": {"": {"model": "%s:block/%s" % (namespace, name)}}})
            written.append(blockstates)
            item_model = _safe_pack_path(
                out_dir,
                Path("assets") / namespace / "models" / "item" / (name + ".json"),
            )
            _write_json(item_model, {"parent": "%s:block/%s" % (namespace, name)})
            written.append(item_model)
            note = out_dir / "BLOCK_MULTI_NOTE.txt"
            note.write_text(
                "The atlas PNG is retained for audit. The generated cube model uses the split top/front/side face PNGs.\n",
                encoding="utf-8",
            )
            written.append(note)
    elif request.form == AssetForm.ENTITY_UV:
        relative = request.target_path or "assets/%s/textures/entity/%s.png" % (namespace, name)
        texture = _safe_pack_path(out_dir, relative)
        texture.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(sprite_path, texture)
        note = out_dir / "ENTITY_UV_NOTE.txt"
        note.write_text(
            "This pack includes the generated texture and uv_layout.json. Vanilla entity overrides must use "
            "the target entity's original path; custom entities need a renderer/model supplied by the mod.\n",
            encoding="utf-8",
        )
        layout = texture.with_name(texture.stem + ".uv_layout.json")
        _write_json(layout, {"regions": to_jsonable(uv_regions or [])})
        written.extend([texture, note, layout])
    else:
        texture = _safe_pack_path(out_dir, Path("assets") / namespace / "textures" / (name + ".png"))
        texture.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(sprite_path, texture)
        written.append(texture)
    return written
